Setup tailwindcss
SantriHub/app pull request #7
Opened 2022-06-12 13:26 UTC by mohamilin

## Description

- Setup tailwindcss in project santrihub

2022-06-13 15:15 UTC, zainfathoni requested changes
Thanks for initiatively making this PR. 🙏 
Overall, it looks good, but I have minor suggestions for this PR.

2022-06-13 15:15 UTC, zainfathoni commented on .all-contributorsrc
> +      ]
Please revert the changes to this file. We shouldn't manually update this file.

We should use GitHub comments to add your name, like what I did here: https://github.com/SantriHub/app/pull/3#issuecomment-1153064029.
You can read more about it over here: https://allcontributors.org/docs/en/bot/usage

2022-06-13 15:22 UTC, zainfathoni commented on package.json
> +    "deploy": "deployctl deploy --prod --include=build,public --project=senarai ./build/index.js",
Btw, I just added the automatic deployment at #8, and it's now deployed at https://santrihub.deno.dev.

2022-06-14 13:01 UTC, mohamilin commented on .all-contributorsrc
> +      ]
Oke, thnks mas @zainfathoni , updated the commits

2022-06-14 13:04 UTC, mohamilin commented on package.json
> +    "deploy": "deployctl deploy --prod --include=build,public --project=senarai ./build/index.js",
oke, thnks mas @zainfathoni

2022-06-14 17:41 UTC, zainfathoni commented on .gitignore
> +/app/tailwind.css
```suggestion
/app/tailwind.css

```

2022-06-14 17:42 UTC, zainfathoni approved these changes
LGTM 💯
Thanks for making the requested changes! 🙏

2022-06-14 17:42 UTC, merged